<?php

namespace Tests\Feature;

use App\Bundles\Landing\Events\FeedBackCreated;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\BaseTestCase;

final class FeedBackTest extends BaseTestCase
{
    use WithFaker;

    private const BASE_URL = '/api/landing/feedbacks';

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->setUpFaker();
    }

    /**
     * @covers \App\Bundles\Landing\Http\Controllers\FeedBackController::store
     */
    public function testStore(): void
    {
        $this->expectsEvents(FeedBackCreated::class);

        $data = [
            'people_title' => $this->faker()->title,
            'people_email' => $this->faker()->email,
            'people_phone' => $this->faker()->phoneNumber,
            'message' => $this->faker()->text(),
        ];

        $response = $this->postJson(static::BASE_URL, $data);

        $response->dump();

        $response->assertOk();

        $decode = $this->decodeResponse($response);

        self::assertNotEmpty($decode);
        self::assertArrayHasKey('success', $decode);
        self::assertTrue($decode['success']);
    }
}
