<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\WithFaker;
use Tests\BaseTestCase;

/**
 * @group BaseTest
 */
class LandingFeedBackTest extends BaseTestCase
{
    use WithFaker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->setUpFaker();
    }

    public function testSend(): void
    {
        $data = [
            'people_title' => $this->faker()->title,
            'people_email' => $this->faker()->email,
            'people_phone' => $this->faker()->phoneNumber,
            'message' => $this->faker()->text(),
        ];

        $response = $this->postJson('/api/landing/send-feedback', $data);

        $response->assertOk();

        $decode = $this->decodeResponse($response);

        self::assertNotEmpty($decode);
        self::assertArrayHasKey('success', $decode);
        self::assertTrue($decode['success']);
    }
}
