<?php

namespace App\Bundles\Product\Providers;

use Illuminate\Support\ServiceProvider;

class ProductProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
